logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    main:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
  loggers:
    mainLogger:
      level: INFO
      handlers: [main]
  root:
    level: DEBUG
    handlers: [main]